name:                tube-bot-fulfillment
version:             0.1.11
synopsis:            Google Assistant Action for TfL Tube Departures
description:         A Google Assistant Action to ask for upcoming Tube departures. Tell your Google Home to talk to Tube Trains to learn more.
homepage:            https://github.com/passy/tube-bot-fulfillment#readme
license:             BSD3
author:              Pascal Hartig
maintainer:          phartig@rdrei.net
copyright:           2016 Pascal Hartig
category:            Web
extra-source-files:
  - README.md
  - stack.yaml
  - test/fixtures/*

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-exported-signatures
  - -Wmissing-local-signatures
  - -Wmonomorphism-restriction

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - dhall
  - digits
  - free
  - hashable
  - lens
  - lens-aeson
  - monad-logger
  - protolude
  - servant-server
  - text
  - text-format
  - unordered-containers
  - vector
  - wai
  - warp
  - wreq

library:
  source-dirs: src
  exposed-modules:
    - Api
    - Common
    - Config
    - Response
    - VersionInfo

executables:
  tube-bot-fulfillment:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - tube-bot-fulfillment

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - tube-bot-fulfillment
      - hspec
      - directory
      - filepath
